site_name: My Tech Docs Docs
site_url: https://fdmsantos.github.io/mytechdocs/
site_description: My Technical documentation
site_author: Fábio Santos
theme:
  name: material
  language: en
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: false
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 5
plugins:
  - glightbox
  - search

nav:
  - Kubernetes:
      - Resources: kubernetes/resources.md
      - Scheduling: kubernetes/scheduling.md
      - Application Configuration: kubernetes/appConfiguration.md
      - Security: kubernetes/security.md
      - Core Components: kubernetes/coreComponents.md
      - Cluster Maintenance: kubernetes/clusterMaintenance.md
      - Helm: kubernetes/helm.md
      - Cilium: kubernetes/cilium.md
      - Rook-Ceph: kubernetes/rook-ceph.md
  - DevOps:
      - Monitoring:
          - Prometheus: devops/monitoring/prometheus.md
          - Alert Manager: devops/monitoring/alertmanager.md
          - Loki: devops/monitoring/loki.md
  - Cloud:
      - Azure:
          - Azure Virtual Desktop: cloud/azure/azd.md
  - Data Engineering:
      - Hadoop:
          - Administration: dataengineering/hadoop/administration.md
          - Setup Cluster: dataengineering/hadoop/setup.md
      - Kafka:
          - Administration: dataengineering/kafka/administration.md
          - Schema Registry: dataengineering/kafka/schema.md
          - Connectors: dataengineering/kafka/connectors.md
      - Spark:
          - Spark: dataengineering/spark/spark.md
          - Databricks: dataengineering/spark/databricks.md
      - Storage Layers:
          - Iceberg: dataengineering/storagelayers/iceberg.md
      - Hive: dataengineering/hive.md
      - Datawarehouse:
          - Basic Concepts: dataengineering/datawarehouse/datawarehouse.md
          - DBT: dataengineering/datawarehouse/dbt.md
          - Azure Synapse: dataengineering/datawarehouse/synapse.md
      - Airflow: dataengineering/airflow.md
  - Programming:
      - Big O: programming/bigo.md
      - Bot Framework: programming/bot-framework.md
  - Unix OS:
      - Apps: unix/apps.md
      - Networking: unix/networking.md
  - Certifications:
      - Azure:
        - Data Engineer Associate:  certifications/azure/azure-data-engineer-associate.md
